# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin" 
  displayName: 'Install rust'

- script: cargo build --release
  displayName: 'Build release'

- task: PublishBuildArtifacts@1
  displayName: Deploy artifact
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/target/release/casino-v1'
    ArtifactName: 'drop'
    publishLocation: 'Container'




